name: bskycli

on:
    workflow_dispatch:

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v2
              with:
                dotnet-version: 8.x

            - uses: dotnet/nbgv@master

            - name: Setup Native AOT prerequisites
              run: sudo apt-get install clang zlib1g-dev
              shell: bash

            - name: Build and Publish bskycli for linux x64
              run: dotnet publish apps/bskycli/bskycli.csproj -c Release -o publish/linux-x64 -r linux-x64

            - name: Upload package x64
              uses: actions/upload-artifact@v2
              with:
                name: linux-x64
                path: publish/linux-x64

            - name: Build and Publish bskycli for linux arm64
              run: dotnet publish apps/bskycli/bskycli.csproj -c Release -o publish/linux-arm64 -r linux-arm64
  
            - name: Upload package arm64
              uses: actions/upload-artifact@v2
              with:
                  name: linux-arm64
                  path: publish/linux-arm64
            


